title: Playwright for Go
email: max@schmitt.mx
description: >- # this means to ignore newlines until "baseurl:"
  Playwright is a Node.js library to automate Chromium, Firefox and WebKit with a single API.
  Playwright is built to enable cross-browser web automation that is ever-green, capable, reliable and fast.
baseurl: "/playwright-go"
url: "https://playwright-community.github.io/"
twitter_username: maxibanki
github_username: playwright-community
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-readme-index
exclude:
  - playwright/
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
